# Generated by Django 3.2.7 on 2021-09-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Data',
        ),
    ]
